powdat<-read.table("housepow.txt",sep=";",header=TRUE)
date1<-subset(powdat,Date=="1/2/2007")
date2<-subset(powdat,Date=="2/2/2007")
finaldat<-rbind(date1,date2)
finaldat$Date<-as.Date(finaldat$Date,'%d/%m/%Y')
finaldat$Date_and_Time<-as.POSIXct(paste(finaldat$Date,finaldat$Time),format="%Y-%m-%d %H:%M:%S")
png(file="plot3.png",width=480,height=480)
plot(finaldat$Date_and_Time,finaldat$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
lines(finaldat$Date_and_Time,finaldat$Sub_metering_2,type="l",col="red")
lines(finaldat$Date_and_Time,finaldat$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1)
dev.off()