powdat<-read.table("housepow.txt",sep=";",header=TRUE)
date1<-subset(powdat,Date=="1/2/2007")
date2<-subset(powdat,Date=="2/2/2007")
finaldat<-rbind(date1,date2)
finaldat$Date<-as.Date(finaldat$Date,'%d/%m/%Y')
finaldat$Date_and_Time<-as.POSIXct(paste(finaldat$Date,finaldat$Time),format="%Y-%m-%d %H:%M:%S")
png(file="plot4.png",width=480,height=480)
par(mfrow=c(2,2),mar=c(4,4,1,1))
plot(finaldat$Date_and_Time,as.numeric(finaldat$Global_active_power)/1000,type="l",ylab="Global Active Power (kilowatts)",xlab="")
plot(finaldat$Date_and_Time,as.numeric(finaldat$Voltage),type="l",ylab="Voltage",xlab="datetime")
plot(finaldat$Date_and_Time,finaldat$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1)
lines(finaldat$Date_and_Time,finaldat$Sub_metering_2,type="l",col="red")
lines(finaldat$Date_and_Time,finaldat$Sub_metering_3,type="l",col="blue")
plot(finaldat$Date_and_Time,as.numeric(finaldat$Global_reactive_power),type="l",ylab="Global_reactive_power",xlab="datetime")
dev.off()